# https://travis-ci.com/kecnry/distl

language: python

addons:
  apt:
    sources:
    # add PPAs with more up-to-date toolchains
    - ubuntu-toolchain-r-test

dist: bionic

env:
    global:
        # Set defaults to avoid repeating in most cases
        - PIP_DEPENDENCIES='nose codecov corner dill'
        - CONDA_DEPENDENCIES='matplotlib scipy'
        - PYTHON_VERSION=2.7
        - NUMPY_VERSION=1.10
        - ASTROPY_VERSION=1.0
        - SCIPY_VERSION=1.3
        - MATPLOTLIB_VERSION=2.2

matrix:

    # Don't wait for allowed failures
    fast_finish: true

    include:

        # Try with lowest supported numpy/astropy/scipy (only with python 2.7)
        - os: linux
          env: PYTHON_VERSION=2.7 NUMPY_VERSION=1.10 ASTROPY_VERSION=1.0 SCIPY_VERSION=1.0

        - os: linux
          env: PYTHON_VERSION=2.7 NUMPY_VERSION=1.12 ASTROPY_VERSION=1.0 SCIPY_VERSION=1.0

        - os: linux
          env: PYTHON_VERSION=2.7 NUMPY_VERSION=1.12 ASTROPY_VERSION=2.0 SCIPY_VERSION=1.0

        - os: linux
          env: PYTHON_VERSION=2.7 NUMPY_VERSION=1.16 ASTROPY_VERSION=2.0 SCIPY_VERSION=1.0

        - os: linux
          env: PYTHON_VERSION=2.7 NUMPY_VERSION=1.12 ASTROPY_VERSION=1.0 SCIPY_VERSION=1.2

        - os: linux
          env: PYTHON_VERSION=2.7 NUMPY_VERSION=1.12 ASTROPY_VERSION=2.0 SCIPY_VERSION=1.2

        - os: linux
          env: PYTHON_VERSION=2.7 NUMPY_VERSION=1.16 ASTROPY_VERSION=2.0 SCIPY_VERSION=1.2

        # - os: osx
        #   env: PYTHON_VERSION=2.7 NUMPY_VERSION=1.10 ASTROPY_VERSION=1.0'

        # Try with stable versions of numpy/astropy
        - os: linux
          env: PYTHON_VERSION=2.7 NUMPY_VERSION=1.12 ASTROPY_VERSION=2.0 SCIPY_VERSION=1.2

        - os: linux
          env: PYTHON_VERSION=2.7 NUMPY_VERSION=1.16 ASTROPY_VERSION=2.0 SCIPY_VERSION=1.2


        # NOTE: scipy 1.3+ and numpy 1.17+ only supports python3
        - os: linux
          env: PYTHON_VERSION=3.6 NUMPY_VERSION=1.17 ASTROPY_VERSION=stable SCIPY_VERSION=1.3

        - os: linux
          env: PYTHON_VERSION=3.6 NUMPY_VERSION=1.19 ASTROPY_VERSION=stable SCIPY_VERSION=1.3

        # - os: osx
        #   env: PYTHON_VERSION=2.7 NUMPY_VERSION=stable ASTROPY_VERSION=stable'

        # - os: osx
        #   env: PYTHON_VERSION=3.6 NUMPY_VERSION=stable ASTROPY_VERSION=stable'

        # Try with dev version of numpy/scipy (only with python 3.6) (note that we allow failures for this build below)
        - os: linux
          env: PYTHON_VERSION=3.6 NUMPY_VERSION=dev ASTROPY_VERSION=stable SCIPY_VERSION=1.4

        # - os: osx
        #   env: PYTHON_VERSION=3.6 NUMPY_VERSION=dev ASTROPY_VERSION=stable'

    allow_failures:
      - env: PYTHON_VERSION=3.6 NUMPY_VERSION=dev ASTROPY_VERSION=stable SCIPY_VERSION=1.4

before_install:
    - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then
        brew update;
      fi;

install:
    - git clone git://github.com/astropy/ci-helpers.git
    - source ci-helpers/travis/setup_conda.sh
    - python setup.py build
    - python setup.py install --user

script:
    - cd tests;
    - nosetests --with-coverage --cover-package=distl -v -s -d;

after_success:
    - codecov
